apiVersion: v1
kind: ConfigMap
metadata:
  name: cosmic-watch-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: cosmic-watch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  VITE_API_URL: {{ .Values.frontend.env.VITE_API_URL | quote }}
  DEBUG: {{ .Values.backend.env.DEBUG | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  CORS_ORIGINS: |
    {{- range .Values.config.corsOrigins }}
    - {{ . }}
    {{- end }}
